name: build portfolio

env:
  CI: false

on:
  push:
    branches:
    - main

jobs:
  building-portfolio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - run: |
          mkdir -p docs
          npm ci
          npm run build
          rm -rf ./node_modules
          echo \"www.tanimsk.me\" > dist/CNAME
      - name: Commit and push changes
        run: |
          git config --local user.email ${{ secrets.USR_EMAIL }}
          git config --local user.name ${{ secrets.USR_NAME }}
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update docs folder"
            git push
          fi
