name: build portfolio

env:
  CI: false

on:
  push:
    branches:
    - main

jobs:
  building-portfolio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - run: |
          mkdir docs
          npm ci
          npm run build
      - name: Commit and push changes
        run: |
          git config --local user.email "sktanim5800@gmail.com"
          git config --local user.name "tanimsk"
          git add .
          git commit -m "Update docs folder"
          git push
